http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

bazel_dep(name = "bazel_features", version = "1.33.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_shell", version = "0.4.1")

bazel_dep(name = "rules_xcodeproj")
local_path_override(
    module_name = "rules_xcodeproj",
    path = "./build-system/bazel-rules/rules_xcodeproj",
)

bazel_dep(name = "rules_apple", version = "4.3.3", repo_name = "build_bazel_rules_apple")
git_override(
    module_name = "rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    commit = "d930c4c6eaeed91c8275604a428407d123a85216",
    patches = [
        "//patches:rules_apple_no_exec_platform_constraint.patch",
        "//patches:rules_apple_create_simulator_action.patch",
        "//patches:rules_apple_alticonstool_fix.patch",
    ],
    patch_strip = 1,
)

bazel_dep(name = "rules_swift", repo_name = "build_bazel_rules_swift")
local_path_override(
    module_name = "rules_swift",
    path = "./build-system/bazel-rules/rules_swift",
)

bazel_dep(name = "apple_support", repo_name = "build_bazel_apple_support")
local_path_override(
    module_name = "apple_support",
    path = "./build-system/bazel-rules/apple_support",
)

bazel_dep(name = "rules_applecross")
git_override(
    module_name = "rules_applecross",
    remote = "https://github.com/apple-cross-toolchain/rules_applecross.git",
    commit = "2bb49eb5f0bc92923903c45fa2c88d23b68e7afd",
)

bazel_dep(name = "xctestrunner", version = "0.0.1")
git_override(
    module_name = "xctestrunner",
    remote = "https://github.com/apple-cross-toolchain/xctestrunner-bash.git",
    commit = "9548d93f29a2a93315d7a0458622682c0f76e6fe",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "llvm", version = "0.6.1")
single_version_override(
    module_name = "llvm",
    patch_strip = 1,
    patches = ["//patches:llvm_glibc_x86_includes.patch"],
    version = "0.6.1",
)

apple_cross_toolchain = use_extension(
    "@rules_applecross//toolchain:extensions.bzl",
    "apple_cross_toolchain",
)
apple_cross_toolchain.configure(
    name = "apple_cross_toolchain",
    apple_sdk_urls = ["SDKS_URL"],
    apple_sdk_sha256 = "22f572b8e2110b076be3623bac9de2a9892b98b2914922f9ae74657afece8b17",
    apple_sdk_archive_type = "tar.xz",
)
use_repo(apple_cross_toolchain, "apple_cross_toolchain")

register_toolchains("@apple_cross_toolchain//:cc-toolchain-ios_arm64")
register_toolchains("@apple_cross_toolchain//:swift-toolchain-ios_arm64")

http_file(
    name = "cmake_tar_gz",
    urls = ["https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz"],
    sha256 = "773cc679c3a7395413bd096523f8e5d6c39f8718af4e12eb4e4195f72f35e4ab",
)

http_file(
    name = "meson_tar_gz",
    urls = ["https://github.com/mesonbuild/meson/releases/download/1.6.0/meson-1.6.0.tar.gz"],
    sha256 = "999b65f21c03541cf11365489c1fad22e2418bb0c3d50ca61139f2eec09d5496",
)

http_file(
    name = "ninja-linux_zip",
    urls = ["https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip"],
    sha256 = "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255",
)

http_file(
    name = "flatbuffers_zip",
    urls = ["https://github.com/google/flatbuffers/archive/refs/tags/v24.12.23.zip"],
    sha256 = "c5cd6a605ff20350c7faa19d8eeb599df6117ea4aabd16ac58a7eb5ba82df4e7",
)

provisioning_profile_repository = use_extension("@build_bazel_rules_apple//apple:apple.bzl", "provisioning_profile_repository_extension")
#provisioning_profile_repository.setup(
#    fallback_profiles = "//path/to/some:filegroup", # Profiles to use if one isn't found locally
#)

bazel_dep(name = "build_configuration")
local_path_override(
    module_name = "build_configuration",
    path = "./build-system/example-configuration",
)

bazel_dep(name = "sourcekit_bazel_bsp", version = "0.7.1")
local_path_override(
    module_name = "sourcekit_bazel_bsp",
    path = "build-system/bazel-rules/sourcekit-bazel-bsp",
)
